language: cpp

matrix:
  include:
    - compiler: gcc
      env: GAZEBO_YARP_PLUGINS_BUILD_TYPE=Debug USE_GAZEBO_ONEDOTNINE=TRUE 
    - compiler: gcc
      env: GAZEBO_YARP_PLUGINS_BUILD_TYPE=Release USE_GAZEBO_THREE=TRUE RUN_TESTS=TRUE
    - compiler: clang
      env: GAZEBO_YARP_PLUGINS_BUILD_TYPE=Debug USE_GAZEBO_THREE=TRUE RUN_TESTS=TRUE
    - compiler: clang
      env: GAZEBO_YARP_PLUGINS_BUILD_TYPE=Release USE_GAZEBO_ONEDOTNINE=TRUE


before_script:
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu precise main" > /etc/apt/sources.list.d/gazebo-latest.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo add-apt-repository -y ppa:robotology/ppa
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get --force-yes install libace-dev libgsl0-dev
  - if [ $USE_GAZEBO_THREE ]; then sudo apt-get install -qq --force-yes libgazebo-dev libavcodec-dev libavformat-dev libswscale-dev; fi
  - if [ $USE_GAZEBO_ONEDOTNINE ]; then sudo apt-get install -qq --force-yes gazebo libtinyxml-dev libboost-system-dev; fi
  # move to /home/travis/build/robotology/ directory
  - cd ..
  # install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCREATE_SHARED_LIBRARY:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DYARP_USE_OPENCV:BOOL=OFF -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} ..
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  
  # launch yarp while you install everything else
  - yarpserver &
  
  # install robot-testing framework
  - git clone https://github.com/robotology/robot-testing
  - cd robot-testing
  - mkdir build 
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} -DENABLE_MIDDLEWARE_PLUGINS:BOOL=ON ..
  - make 
  - sudo make install
  # by default /usr/local/lib is not in the search path of dlopen
  # so we add it to LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - sudo ldconfig
  - cd ../..
  
  # install icub-tests 
  - git clone https://github.com/robotology/icub-tests
  - cd icub-tests
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} ..
  - make 
  - export YARP_DATA_DIRS=${YARP_DATA_DIRS}:/home/travis/build/robotology/icub-tests/suits
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/travis/build/robotology/icub-tests/build/plugins
  - sudo ldconfig
  - cd ../..
  
  # install icub-gazebo (for testing)
  - git clone https://github.com/robotology-playground/icub-gazebo
  - export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:/home/travis/build/robotology/icub-gazebo
  # export icub-gazebo in GAZEBO_RESOURCE_PATH (see https://bitbucket.org/osrf/gazebo/issue/1607/gazebo-does-not-start-if-the#comment-18101826 )
  - source /usr/share/gazebo/setup.sh
  - export GAZEBO_RESOURCE_PATH=${GAZEBO_RESOURCE_PATH}:/home/travis/build/robotology/icub-gazebo
  
  # compile gazebo-yarp-plugins
  - cd gazebo-yarp-plugins
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} -DALLOW_IDL_GENERATION:BOOL=OFF ./..
  - pwd

script: 
  - make
  # test install/uninstall
  - sudo make install
  - export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:/usr/local/lib 
  # run tests
  #- if [ $RUN_TESTS ]; then gzserver & fi
  #- sleep 10
  # - yarp name list 
  #- if [ $RUN_TESTS ]; then pkill gzserver; fi
  - if [ $RUN_TESTS ]; then testrunner --verbose --suit ../../icub-tests/suits/basics-icubGazeboSim.xml; fi
  - sudo make uninstall
  - pkill yarpserver

notifications:
  email:
    - pegua1@gmail.com
